# Generated by Django 5.1.3 on 2024-11-28 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi')),
                ('airplane_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='airplane_types', to='airplane_manufacturing_application.airplanetype')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('airplane', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='airplane_manufacturing_application.airplane')),
                ('airplane_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airplane_manufacturing_application.airplanetype')),
                ('part_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='airplane_manufacturing_application.parttype')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('is_assembly_team', models.BooleanField(default=False)),
                ('part_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airplane_manufacturing_application.parttype')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='airplane_manufacturing_application.team')),
            ],
        ),
    ]
